### ISSUE TITLE
Not working in Chrome 79

### ISSUE THREAD

**Issue by raulesperante** [firephp/firephp-for-browser-devtools#54]
My version is  79.0.3945.88 (Official Build) (64-bit)

I can not see logs in the FirePHP console when visiting http://firephp.org/

**Comment by cadorn** [comment]
Seems to be working for me with: 80.0.3987.87 (Official Build) (64-bit)

Can you confirm?

Did you enable it properly? (Enabled `FirePHPCore` header in settings and enable it for the domain)

**Comment by stSaHiB** [comment]
Chrome Version 80.0.3987.87 - works for me to. Also no problems in Chromium

**Comment by cadorn** [comment]
@stSaHiB Thanks for checking!

Closing due to: Likely user error.
