### ISSUE TITLE
Upgrade build tooling (mozilla add-ons listing down)

### ISSUE THREAD

**Issue by cadorn** [firephp/firephp-for-browser-devtools#57]
The build tooling is currently failing.

It needs to be upgraded to the latest tech.

**Comment by cadorn** [comment]
A mozilla extension reviewer is unable to build the extension.

**Comment by cadorn** [comment]
I have been working on updating the libraries underlying the extension to a new build system. I am about to update the extension.

**Comment by jeeba** [comment]
Yes please, your tool was awesome. I was looking for it. Is there a way to make it work also on Firefox Developer Edition?

**Comment by stSaHiB** [comment]
I'm using it on FF developer Edition (and Chrome if I need 2 Browsers) - it's working.
but you are right with one thing: it's awesome :-)

**Comment by jeeba** [comment]
@stSaHiB  ¿Where do you find the PlugIn on FF Dev? I can't find it on the Firefox Repository :(

**Comment by cadorn** [comment]
@jeeba The **mozilla add-ons listing is currently down** until I publish a new release that passes review.

You can install the extension from here in the meantime: https://github.com/firephp/firephp-for-browser-devtools#local

**Comment by cadorn** [comment]
I have a new preview build **1.4.2 pre** to test for regressions: https://github.com/firephp/firephp-for-browser-devtools/tree/pre/dist

It is from this PR: https://github.com/firephp/firephp-for-browser-devtools/pull/59

It should work on **Firefox, Chrome & Brave**.

Just a bit more work and the extension can be built from source. I'll then submit to addons and chrome store.

Then on to bug fixes and new features! :D

**Comment by cadorn** [comment]
A new release has been submitted to Mozilla & Google for review: https://github.com/firephp/firephp-for-browser-devtools/releases/tag/v1.4.6

Will take up to several weeks for manual review by them.

**Comment by cadorn** [comment]
Another new release with a better permissions grant flow for chrome has been submitted. The user is now asked to grant permissions for every hostname specifically so the extension does not need access to all hostnames by default.

This `optional_permissions` feature is not working on firefox as the `webRequest` API does not get events when granting permissions to a new hostname. On firefox, the user must still grant all permissions from the start. See: https://github.com/firephp/firephp-for-browser-devtools/issues/63

**Comment by cadorn** [comment]
A new build has been submitted to Mozilla: https://github.com/firephp/firephp-for-browser-devtools/releases/tag/v1.5.7

It should pass manual approval now and stay up.
